import { SurveySchema } from './types';

export const educationalSurveySchema: SurveySchema = {
  surveyType: 'educational-survey',
  title: 'Survey Report - Educational',
  steps: [
    {
      id: 1,
      title: 'General Information',
      description: 'General info and facility details',
      sections: [
        {
          id: 'general-info',
          title: 'General Information',
          fields: [
            { key: 'eduSurveyDate', label: 'Date', type: 'date', required: true },
            { key: 'eduInstituteName', label: 'Name of the Institute', type: 'text', required: true },
            { key: 'eduAddress', label: 'Address', type: 'textarea', className: 'md:col-span-2', required: true },
            { key: 'eduContactPerson', label: 'Contact Person/ Designation (Customer)', type: 'text', required: true },
            { key: 'eduSurveyDoneBy', label: 'Survey Done by-', type: 'text', required: true },
          ],
        },
        {
          id: 'facility-details',
          title: 'Facility Details',
          fields: [
            { key: 'eduBuiltUpArea', label: 'Built up Area:', type: 'text', required: true },
            { key: 'eduCleanableArea', label: 'Cleanable Area:', type: 'text', required: true },
            { key: 'eduExternalArea', label: 'External Area:', type: 'text', required: true },
            { key: 'eduCarParkArea', label: 'Car park (External/Basement) Area', type: 'text', required: true },
            { key: 'eduTerraceArea', label: 'Terrace Area', type: 'text', required: true },
            { key: 'eduSumpCleaning', label: 'Sump & Water Tank cleaning', type: 'text', required: true },
            { key: 'eduServiceProvider', label: 'Current Service provider', type: 'text', required: true },
            { key: 'eduCompetitors', label: 'Key players / competition in the vicinity / area / building premises', type: 'text', required: true },
            { key: 'eduInsuranceRequired', label: 'Any additional insurance required by the client - If Yes, do share the checklist towards the same & the requirement accordingly', type: 'text', required: true },
            { key: 'eduInsuranceType1', label: 'Type 1.', type: 'text' },
            { key: 'eduInsuranceType2', label: 'Type 2.', type: 'text' },
            { key: 'eduInsuranceType3', label: 'Type 3.', type: 'text' },
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Cleanable Areas & Services',
      description: 'Cleanable area details and additional services',
      hasCustomComponent: true,
      customComponentId: 'cleanable-areas',
    },
    {
      id: 3,
      title: 'Academic Details',
      description: 'Specific details about classrooms and cleaning frequencies',
      sections: [
        {
          id: 'educational-facility-details',
          title: 'Educational Facility Details',
          fields: [
            { key: 'totalStaircases', label: 'Total nos of Staircase', type: 'text' },
            { key: 'eduStudentCount', label: 'Total No. of Students', type: 'text' },
            { key: 'eduClassroomCount', label: 'Total nos of Classroom', type: 'text' },
            { key: 'eduClassroomCleanFrequency', label: 'Cleaning of class rooms & frequency', type: 'text' },
            { key: 'eduClassroomCleanTimings', label: 'Timings for cleaning of class rooms', type: 'time' },
            { key: 'eduResCleanFrequency', label: 'Cleaning of Residential & frequency', type: 'text' },
            { key: 'eduResCleanTimings', label: 'Timings for cleaning Residential rooms', type: 'time' },
            { key: 'eduResStudentCount', label: 'Total No. of Students residing at the facility', type: 'text' },
            { key: 'eduExistingCleanMethod', label: 'Cleaning Methodology (Existing)', type: 'text' },
            { key: 'eduSuggestedCleanMethod', label: 'Cleaning Methodology (Suggested)', type: 'text' },
            { key: 'eduCafeteriaCleanFrequency', label: 'Cleaning of Cafeteria & frequency', type: 'text' },
            { key: 'eduNightShiftAllowed', label: 'Is cleaning in Night shifts allowed - (In class rooms & Office area)', type: 'text' },
            { key: 'eduCampusCleanIncluded', label: 'Is Campus Cleaning under scope', type: 'text' },
            { key: 'eduToiletriesRequired', label: 'Toiletries to be provided (YES/NO) if yes indicate details', type: 'text' },
            { key: 'eduFacadeGlassArea', label: 'Total external Façade glass area(if to be cleaned) Please provide frequency of cleaning.', type: 'text' },
            { key: 'eduLinersRequired', label: 'Dustbin Liners in scope or not- if yes indicate details of size and change frequency', type: 'text' },
            { key: 'eduLibraryArea', label: 'Library Area', type: 'text' },
            { key: 'eduKitchenDetails', label: 'Kitchen', type: 'text' },
            {
              key: 'eduPestControl',
              label: 'Pest control services(Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'eduCarpentry',
              label: 'Carpentry Services (Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'eduPlumbing',
              label: 'Plumbing Services required (Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'eduHorticulture',
              label: 'Horticulture Services(If yes,indicate details)',
              type: 'textarea',
              className: 'md:col-span-2',
            },
            { key: 'eduLandscaping', label: 'Landscaping area', type: 'text' },
            { key: 'eduIndoorPlants', label: 'Indoor plants  ( Type and qty.)', type: 'text' },
            { key: 'eduWasteType', label: 'Type of Waste', type: 'text' },
            {
              key: 'eduWasteSegregation',
              label: 'Waste segregation & Disposal',
              type: 'textarea',
              className: 'md:col-span-2',
            },
            {
              key: 'eduOfficeBoysRequired',
              label: 'Office Boys Services required (YES/NO)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'eduOfficeBoysSow',
              label: 'SOW Office Boys',
              type: 'textarea',
              className: 'md:col-span-2',
            },
            {
              key: 'eduTechnicalServicesRequired',
              label: 'If Technical Services required please fill in the Technical Survey',
              type: 'textarea',
              className: 'md:col-span-2',
            },
            {
              key: 'eduSpecialChemical',
              label: 'Special Cleaning Chemical Required (Provide the Name & Consumption Details )',
              type: 'textarea',
              className: 'md:col-span-2',
            },
          ],
        },
      ],
    },
    {
      id: 4,
      title: 'Washrooms & Compliance',
      description: 'Washrooms and compliance requirements',
      sections: [
        {
          id: 'gents-washroom',
          title: 'Gents Washroom Details',
          fields: [
            { key: 'eduGentsWashrooms', label: 'No. of Gents Wash Room', type: 'text' },
            { key: 'eduGentsUrinals', label: 'No of Urinal pots', type: 'text' },
            { key: 'eduGentsWc', label: 'No of WC', type: 'text' },
            { key: 'eduGentsBasins', label: 'No of Wash basin', type: 'text' },
            { key: 'eduGentsMirrors', label: 'Mirrors', type: 'text' },
          ],
        },
        {
          id: 'ladies-washroom',
          title: 'Ladies Washroom Details',
          fields: [
            { key: 'eduLadiesWashrooms', label: 'No. of Ladies Wash Room', type: 'text' },
            { key: 'eduLadiesWc', label: 'No of WC', type: 'text' },
            { key: 'eduLadiesBasins', label: 'No of Wash basin', type: 'text' },
            { key: 'eduLadiesMirrors', label: 'Mirrors', type: 'text' },
          ],
        },
        {
          id: 'handicap-washroom',
          title: 'Handicap Washroom Details',
          fields: [
            { key: 'eduHandicapWashrooms', label: 'No. of Handicap Wash Room', type: 'text' },
          ],
        },
        {
          id: 'compliance-requirements',
          title: 'Compliance & Client Requirements',
          fields: [
            { key: 'eduWomenTransport', label: 'Will the client allow our women employees to use the transport facility which they have for their own women employees (in case of late working hours)', type: 'text' },
            { key: 'eduNightShiftAllowance', label: 'Night shift personnels to be provided with necessary night allowances', type: 'text' },
            { key: 'eduUnionActivityCurrent', label: 'Any Union / IR activities with the current vendor?', type: 'text' },
            { key: 'eduUnionActivityArea', label: 'Any Union / IR activities with the specific area / vicinity?', type: 'text' },
            { key: 'eduGratuityClearance', label: 'The Gratuity or any other liability due, to take over staff must be cleared by the current vendor to avoid any future liability ues', type: 'text' },
            { key: 'eduPwdHiring', label: 'Is the Client willing to hire PWD (People with Disability – hearing and speech impaired / orthopedics etc) - all these sections of people have a great need as well as immense stability for a job, we will ensure we fit them in jobs where their disability is not a hindrance', type: 'text' },
            { key: 'eduSpecificCompliance', label: 'Any specific compliance requirements - Do mentioned the requirement in detail', type: 'text' },
            { key: 'eduWageStructure', label: 'What are the specific requirements for the Zone / Industry wages - Do list the same along with applicable leave wages as per ACT', type: 'text' },
            { key: 'eduSalaryComponent', label: 'Does the client want any specific salary components to be disbursed monthly / annually ie leave encashment / bonus (we must avoid giving leave encashment monthly instead quote a competitive salary so our employees feel well paid)', type: 'text' },
            { key: 'eduVerification', label: 'Does the client have a specific requirement of background / police / Medical verification. Do share the checklist in case of any specific checks if required', type: 'text' },
            { key: 'eduBiometric', label: 'Requirement of Biometric?', type: 'text' },
            { key: 'eduItInfra', label: 'IT infrastructure requirement - (Laptop, Desktop & data/network connection): Will the said infrastructure provided by customer or will be on chargeable basis?', type: 'text' },
            { key: 'eduHighRisk', label: 'It is ensured that service/ facility does not classify as high risk environments - High Risk Environment classification (Aviation, nuclear sites, data centers, critical banking facilities including financial trading floors, major communication hubs, control centers, major call centers, clean room/classified cleaning areas in pharmaceutical or food production facilities, critical healthcare facilities, schools & colleges, hospitals, transport, catering, processing of personally identifiable information (e.g. name, DOB, PAN etc.), integrated facility services, Public Financial Institution/Public Private Partnership, pure advisory service, transport of money and valuables, confidential waste, hazardous chemicals, use of drones, service rendered in remote areas.', type: 'text' },
            { key: 'eduBvgChecklist', label: 'If service is rendered in high risk environments, background check will be done for all employees and stored locally & a BCP plan will be set up in consultation of HQ Risk team (if service is low risk answer yes & If YES for high risk, do indicate the checklist for BGV accordingly', type: 'text' },
            { key: 'eduOtherDetails', label: 'Other Details if any:', type: 'textarea', className: 'md:col-span-2' },
          ],
        },
      ],
    },
    {
      id: 5,
      title: 'Equipment Deployment',
      description: 'Current and suggested cleaning equipment',
      hasCustomComponent: true,
      customComponentId: 'educational-equipment',
    },
    {
      id: 6,
      title: 'Manpower Deployment',
      description: 'Current and suggested manpower deployment',
      hasCustomComponent: true,
      customComponentId: 'educational-manpower',
    },
  ],
};
