import { SurveySchema } from './types';

export const guestHouseSurveySchema: SurveySchema = {
  surveyType: 'guest-house-survey',
  title: 'Survey Report - Guest House',
  steps: [
    {
      id: 1,
      title: 'General Information',
      description: 'General info and facility details',
      sections: [
        {
          id: 'general-info',
          title: 'General Information',
          fields: [
            { key: 'guestSurveyDate', label: 'Date', type: 'date', required: true },
            { key: 'guestClientName', label: 'Name of the Client', type: 'text', required: true },
            { key: 'guestAddress', label: 'Address', type: 'textarea', className: 'md:col-span-2', required: true },
            { key: 'guestContactPerson', label: 'Contact Person/ Designation', type: 'text', required: true },
            { key: 'guestContactNumbers', label: 'Phone no. , Fax no and mobile no.', type: 'text', required: true },
            { key: 'guestSurveyDoneBy', label: 'Survey Done by- (Designation/Ph. No)', type: 'text', required: true },
          ],
        },
        {
          id: 'facility-details',
          title: 'Facility Details',
          fields: [
            { key: 'guestBuiltUpArea', label: 'Built up Area:', type: 'text', required: true },
            { key: 'guestCleanableArea', label: 'Cleanable Area:', type: 'text', required: true },
            { key: 'guestFloorCount', label: 'No. of Floors (Please provide Floor plate area)', type: 'text', required: true },
            { key: 'guestFlooringType', label: 'Type of flooring', type: 'text', required: true },
            { key: 'guestRoomCount', label: 'Number of Rooms', type: 'text', required: true },
            { key: 'guestOccupancyType', label: 'Occupancy Type- Double/Single', type: 'text', required: true },
            { key: 'guestWashRoomCount', label: 'No of Wash Rooms', type: 'text', required: true },
            { key: 'guestServiceProvider', label: 'Current Service provider', type: 'text', required: true },
            { key: 'guestCompetitors', label: 'Key players / competition in the vicinity / area / building premises', type: 'text', required: true },
            { key: 'guestInsuranceRequired', label: 'Any additional insurance required by the client - If Yes, do share the checklist towards the same & the requirement accordingly', type: 'text', required: true },
            { key: 'guestInsuranceType1', label: 'Type 1.', type: 'text' },
            { key: 'guestInsuranceType2', label: 'Type 2.', type: 'text' },
            { key: 'guestInsuranceType3', label: 'Type 3.', type: 'text' },
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Cleanable Areas & Services',
      description: 'Cleanable area details and summaries',
      hasCustomComponent: true,
      customComponentId: 'cleanable-areas',
    },
    {
      id: 3,
      title: 'Operational Details',
      description: 'Expected occupancy, amenities, services, and utilities',
      sections: [
        {
          id: 'guest-house-operations',
          title: 'Guest House Operational Details',
          fields: [
            { key: 'guestExpectedOccupancy', label: 'Expected Occupancy %', type: 'text' },
            { key: 'guestExternalAreaSft', label: 'External Area: (Sft)', type: 'text' },
            { key: 'guestRoomAmenities', label: 'Room Amenities: Please provide details', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestToiletriesDetails', label: 'Toiletries to be provided or not, if yes provide details.', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestBasementArea', label: 'Basement (Area)', type: 'text' },
            { key: 'guestLinersDetails', label: 'Dustbin Liners in scope or not- if yes provide details of size and change frequency', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestGym', label: 'Gym', type: 'text' },
            {
              key: 'guestShowerRoomsCount',
              label: 'No of shower rooms',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'guestLibraryCount',
              label: "Library: (No's)",
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'guestKitchenDetails',
              label: 'Kitchen',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            { key: 'guestPaintingsCount', label: 'No. of paintings, if any', type: 'text' },
            { key: 'guestCarPark', label: 'Car park (External/Basement)', type: 'text' },
            { key: 'guestTerraceTanks', label: 'Terrace (No. of water tanks)', type: 'text' },
            { key: 'guestStaffAccommodation', label: 'Accommodation for  staff ', type: 'text' },
            { key: 'guestStaffFood', label: 'Food for  Staff ', type: 'text' },
            { key: 'guestKitchenEquipment', label: 'All Kitchen Equipment ', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestCutleryCrockery', label: 'Cutlery and Crockery', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestBedBathLinen', label: 'Bed & Bath Linen', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestFuelGas', label: 'Fuel (Gas)', type: 'text' },
            { key: 'guestAppliances', label: 'Refrigerator / Deep freezers/ Washing Machine', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestCateringServices', label: 'Catering Services', type: 'text' },
            { key: 'guestMenu', label: 'Menu', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestBillingCatering', label: 'Billing details  for catering services (By client / Guest)', type: 'text' },
            { key: 'guestWasteManagement', label: 'Waste segregation & Disposal', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestOtherDetails', label: 'Other Details if any', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestGeneratorUps', label: 'Generator / UPS ', type: 'text' },
            { key: 'guestBillPayments', label: 'Electricity /Water/Telephone bill Payments ', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestMediaPayments', label: 'News Paper/ Magazines/Cable TV connection Payments ', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestLaundryServices', label: 'Laundry Services (Provide Details)', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestFacadeGlass', label: 'Total external Façade glass area(if to be cleaned) Please provide frequency of cleaning.', type: 'text' },
            {
              key: 'guestCarpentry',
              label: 'Carpentry Services (Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'guestPlumbing',
              label: 'Plumbing Services required (Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'guestPestControl',
              label: 'Pest control services(Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            { key: 'guestHorticulture', label: 'Horticulture Services(If yes, provide details)', type: 'textarea', className: 'md:col-span-2' },
            { key: 'guestLandscaping', label: 'Landscaping area', type: 'text' },
            { key: 'guestIndoorPlants', label: 'Indoor plants  ( Type and qty.)', type: 'text' },
          ],
        },
      ],
    },
    {
      id: 4,
      title: 'Compliance & Legal',
      description: 'Compliance and HR/legal requirements',
      sections: [
        {
          id: 'compliance-requirements',
          title: 'Compliance & Client Requirements',
          fields: [
            { key: 'guestWomenTransport', label: 'Will the client allow our women employees to use the transport facility which they have for their own women employees (in case of late working hours) ', type: 'text' },
            { key: 'guestNightShiftAllowance', label: 'Night shift personnels to be provided with necessary night allowances', type: 'text' },
            { key: 'guestUnionActivityCurrent', label: 'Any Union / IR activities with the current vendor?', type: 'text' },
            { key: 'guestUnionActivityArea', label: 'Any Union / IR activities with the specific area / vicinity?', type: 'text' },
            { key: 'guestGratuityClearance', label: 'The Gratuity or any other liability due, to take over staff must be cleared by the current vendor to avoid any future liability ues', type: 'text' },
            { key: 'guestPwdHiring', label: 'Is the Client willing to hire PWD (People with Disability – hearing and speech impaired / orthopedics etc) - all these sections of people have a great need as well as immense stability for a job, we will ensure we fit them in jobs where their disability is not a hindrance', type: 'text' },
            { key: 'guestSpecificCompliance', label: 'Any specific compliance requirements - Do mentioned the requirement in detail', type: 'text' },
            { key: 'guestWageStructure', label: 'What are the specific requirements for the Zone /  Industry wages - Do list the same along with applicable leave wages as per ACT ', type: 'text' },
            { key: 'guestSalaryComponent', label: 'Does the client want any specific salary components to be disbursed monthly / annually ie leave encashment / bonus (we must avoid giving leave encashment monthly instead quote a competitive salary so our employees feel well paid)', type: 'text' },
            { key: 'guestVerification', label: 'Does the client have a specific requirement of background / police / Medical  verification. Do share the checklist in case of any specific checks if required ', type: 'text' },
            { key: 'guestBiometric', label: 'Requirement of Biometric?', type: 'text' },
            { key: 'guestItInfra', label: 'IT infrastructure requirement - (Laptop, Desktop & data/network connection): Will the said infrastructure provided by customer or will be on chargeable basis? ', type: 'text' },
            { key: 'guestHighRisk', label: 'It is ensured that service/ facility does not classify as high risk environments - High Risk Environment classification (Aviation, nuclear sites, data centers, critical banking facilities including financial trading floors, major communication hubs, control centers, major call centers, clean room/classified cleaning areas in pharmaceutical or food production facilities, critical healthcare facilities, schools & colleges, hospitals, transport, catering, processing of personally identifiable information (e.g. name, DOB, PAN etc.), integrated facility services, Public Financial Institution/Public Private Partnership, pure advisory service, transport of money and valuables, confidential waste, hazardous chemicals, use of drones, service rendered in remote areas.', type: 'text' },
            { key: 'guestBvgChecklist', label: 'If service is rendered in high risk environments, background check will be done for all employees and stored locally & a BCP plan will be set up in consultation of HQ Risk team (if service is low risk answer yes & If YES for high risk, do indicate the checklist for BGV accordingly ', type: 'text' },
            { key: 'guestOtherDetails2', label: 'Other Details if any:', type: 'textarea', className: 'md:col-span-2' },
          ],
        },
      ],
    },
    {
      id: 5,
      title: 'Equipment Deployment',
      description: 'Current and suggested cleaning equipment',
      hasCustomComponent: true,
      customComponentId: 'educational-equipment',
    },
    {
      id: 6,
      title: 'Manpower Deployment',
      description: 'Current and suggested manpower deployment',
      hasCustomComponent: true,
      customComponentId: 'educational-manpower',
    },
    {
      id: 7,
      title: 'Guest Amenities',
      description: 'Guest amenities details and quantity to be provided',
      hasCustomComponent: true,
      customComponentId: 'guest-amenities',
    },
  ],
};
