import { SurveySchema } from './types';

export const hotelsSurveySchema: SurveySchema = {
  surveyType: 'hotels-survey',
  title: 'Survey Report - Hotels',
  steps: [
    {
      id: 1,
      title: 'General Information',
      description: 'General info and facility details',
      sections: [
        {
          id: 'general-info',
          title: 'General Information',
          fields: [
            { key: 'hotelSurveyDate', label: 'Date', type: 'date', required: true },
            { key: 'hotelName', label: 'Name of the Hotel / Restaurant', type: 'text', required: true },
            { key: 'hotelAddress', label: 'Address', type: 'textarea', className: 'md:col-span-2', required: true },
            { key: 'hotelContactPerson', label: 'Contact Person/ Designation', type: 'text', required: true },
            { key: 'hotelContactNumbers', label: 'Phone no. , Fax no and mobile no.', type: 'text', required: true },
            { key: 'hotelSurveyDoneBy', label: 'Survey Done by- (Designation/Ph. No)', type: 'text', required: true },
          ],
        },
        {
          id: 'facility-details',
          title: 'Facility Details',
          fields: [
            { key: 'hotelWorkTimings', label: 'Work Timings of Client with Shift details (Work Hours/Shift Time)', type: 'text', required: true },
            { key: 'hotelWorkingDays', label: "CLIENT'S Working Days (24/7,24/5,6 days etc..)", type: 'text', required: true },
            { key: 'hotelServiceRequired', label: 'service required (24/7, 24/6, 24/5, etc..)', type: 'text', required: true },
            { key: 'hotelBuiltUpArea', label: 'Built up Area:', type: 'text', required: true },
            { key: 'hotelCleanableArea', label: 'Cleanable Area:', type: 'text', required: true },
            { key: 'hotelServiceProvider', label: 'Current Service provider', type: 'text', required: true },
            { key: 'hotelCompetitors', label: 'Key players / competition in the vicinity / area / building premises', type: 'text', required: true },
            { key: 'hotelStaffCategory', label: 'Category of staff to be provided ( Housekeeping  Boys, Bell Boys , stewards Etc..)', type: 'text', required: true },
            { key: 'hotelStaffSkill', label: 'Skill level of the staff to be provided (Skilled, Unskilled, Experienced, Etc…)', type: 'text', required: true },
            { key: 'hotelInsuranceRequired', label: 'Any additional insurance required by the client - If Yes, do share the checklist towards the same & the requirement accordingly', type: 'text', required: true },
            { key: 'hotelInsuranceType1', label: 'Type 1.', type: 'text' },
            { key: 'hotelInsuranceType2', label: 'Type 2.', type: 'text' },
            { key: 'hotelInsuranceType3', label: 'Type 3.', type: 'text' },
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Cleanable Areas & Services',
      description: 'Cleanable area details and summaries',
      hasCustomComponent: true,
      customComponentId: 'cleanable-areas',
    },
    {
      id: 3,
      title: 'Operational Details',
      description: 'Hotel/Restaurant operations, areas, and amenities',
      sections: [
        {
          id: 'hotel-operations',
          title: 'Hotel Operational Details',
          fields: [
            { key: 'hotelExternalArea', label: 'External Area:', type: 'text' },
            { key: 'hotelCarParkArea', label: 'Car park (External/Basement) Area', type: 'text' },
            { key: 'hotelTerraceArea', label: 'Terrace Area', type: 'text' },
            { key: 'hotelSumpCleaning', label: 'Sump & Water Tank cleaning ', type: 'text' },
            { key: 'hotelGuestRooms', label: 'No. of Guest Rooms', type: 'text' },
            { key: 'hotelBanquetHalls', label: 'No. of  Banquet Halls &  Area (Sq ft)', type: 'text' },
            { key: 'hotelRestaurants', label: 'No. of  Restaurant / Lounges & Area (Sq ft)', type: 'text' },
            { key: 'hotelKitchens', label: 'No. of Kitchens', type: 'text' },
            { key: 'hotelFloors', label: 'No. of Floors', type: 'text' },
            { key: 'totalStaircases', label: 'Nos of staircase', type: 'text' },
            {
              key: 'hotelStaffWashrooms',
              label: 'No. of Staffs wash rooms',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'hotelVisitorWashrooms',
              label: 'No. of Visitors wash room',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'hotelBedMakingSow',
              label: 'Bed Making in SOW (YES/NO)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'hotelKitchenStewarding',
              label: 'Kitchen Stewarding under scope (Yes / NO)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'hotelWashingUnderScope',
              label: 'Glass Ware, Cutlery & Crockery, Pots & Pans  washing under scope(Yes / NO)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            { key: 'hotelCafeteriaArea', label: 'Cafeteria Area', type: 'text' },
            { key: 'hotelCafeteriaSow', label: 'Cafeteria SOW', type: 'textarea', className: 'md:col-span-2' },
            { key: 'hotelToiletriesDetails', label: 'Toiletries to be provided  (YES/NO) if yes indicate details', type: 'textarea', className: 'md:col-span-2' },
            {
              key: 'hotelGuestAmenities',
              label: 'Guest Amenities  to be provided  (Yes / No )',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'hotelInventoryAmenities',
              label: 'Inventory of Amenities  under scope   (Yes / No )',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            { key: 'hotelLinersDetails', label: 'Dustbin Liners  / Garbage bags in scope or not- if yes indicate details of size and change frequency', type: 'textarea', className: 'md:col-span-2' },
            { key: 'hotelWasteType', label: 'Type of Waste ', type: 'text' },
            { key: 'hotelWasteSegregation', label: 'Waste segregation & Disposal', type: 'textarea', className: 'md:col-span-2' },
            {
              key: 'hotelStaffFood',
              label: 'Food for  Staff Provided by client (Yes / No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            { key: 'hotelFacadeGlass', label: 'Total external Façade glass area(if to be cleaned) Please provide frequency of cleaning.', type: 'text' },
            {
              key: 'hotelPestControl',
              label: 'Pest control services(Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'hotelCarpentry',
              label: 'Carpentry Services (Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            {
              key: 'hotelPlumbing',
              label: 'Plumbing Services required (Yes/No)',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            { key: 'hotelHorticulture', label: 'Horticulture Services(If yes, indicate details)', type: 'textarea', className: 'md:col-span-2' },
            { key: 'hotelLandscaping', label: 'Landscaping area ', type: 'text' },
            { key: 'hotelIndoorPlants', label: 'Indoor plants  ( Type and qty.)', type: 'text' },
            { key: 'hotelTechnicalRequired', label: 'If Technical Services required please fill in the Technical Survey ', type: 'textarea', className: 'md:col-span-2' },
            { key: 'hotelPorters', label: 'Porters : (Yes/No) If yes provide details.(Quantum of Shifting & Inter Facility or across facility)', type: 'textarea', className: 'md:col-span-2' },
            { key: 'hotelIndoorPlantsSupply', label: 'Indoor plants  whether to be supplied or only maintenance ', type: 'text' },
            {
              key: 'hotelWaterBodiesMaint',
              label: 'Maintenance of water bodies (YES/NO) ',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            { key: 'hotelWaterBodiesDetails', label: 'If YES indicate details', type: 'textarea', className: 'md:col-span-2' },
            { key: 'hotelPaintings', label: 'No. of paintings, if any', type: 'text' },
            {
              key: 'hotelSwimmingPoolMaint',
              label: 'Maintenance of Swimming Pool (YES/NO) ',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
                { label: 'N/A', value: 'na' },
              ],
            },
            { key: 'hotelDrainCleaning', label: 'Storm water,  Drain cleaning ( If yes provide length of Drain)', type: 'text' },
            { key: 'hotelDataCentreCleaning', label: 'Specialized cleaning for Data Centre / Lab - Frequency ', type: 'text' },
          ],
        },
      ],
    },
    {
      id: 4,
      title: 'Compliance & Legal',
      description: 'Compliance and HR/legal requirements',
      sections: [
        {
          id: 'compliance-requirements',
          title: 'Compliance & Client Requirements',
          fields: [
            { key: 'hotelWomenTransport', label: 'Will the client allow our women employees to use the transport facility which they have for their own women employees (in case of late working hours) ', type: 'text' },
            { key: 'hotelNightShiftAllowance', label: 'Night shift personnels to be provided with necessary night allowances', type: 'text' },
            { key: 'hotelUnionActivityCurrent', label: 'Any Union / IR activities with the current vendor?', type: 'text' },
            { key: 'hotelUnionActivityArea', label: 'Any Union / IR activities with the specific area / vicinity?', type: 'text' },
            { key: 'hotelGratuityClearance', label: 'The Gratuity or any other liability due, to take over staff must be cleared by the current vendor to avoid any future liability ues', type: 'text' },
            { key: 'hotelPwdHiring', label: 'Is the Client willing to hire PWD (People with Disability – hearing and speech impaired / orthopedics etc) - all these sections of people have a great need as well as immense stability for a job, we will ensure we fit them in jobs where their disability is not a hindrance', type: 'text' },
            { key: 'hotelSpecificCompliance', label: 'Any specific compliance requirements - Do mentioned the requirement in detail', type: 'text' },
            { key: 'hotelWageStructure', label: 'What are the specific requirements for the Zone /  Industry wages - Do list the same along with applicable leave wages as per ACT ', type: 'text' },
            { key: 'hotelSalaryComponent', label: 'Does the client want any specific salary components to be disbursed monthly / annually ie leave encashment / bonus (we must avoid giving leave encashment monthly instead quote a competitive salary so our employees feel well paid)', type: 'text' },
            { key: 'hotelVerification', label: 'Does the client have a specific requirement of background / police / Medical  verification. Do share the checklist in case of any specific checks if required ', type: 'text' },
            { key: 'hotelBiometric', label: 'Requirement of Biometric?', type: 'text' },
            { key: 'hotelItInfra', label: 'IT infrastructure requirement - (Laptop, Desktop & data/network connection): Will the said infrastructure provided by customer or will be on chargeable basis? ', type: 'text' },
            { key: 'hotelHighRisk', label: 'It is ensured that service/ facility does not classify as high risk environments - High Risk Environment classification (Aviation, nuclear sites, data centers, critical banking facilities including financial trading floors, major communication hubs, control centers, major call centers, clean room/classified cleaning areas in pharmaceutical or food production facilities, critical healthcare facilities, schools & colleges, hospitals, transport, catering, processing of personally identifiable information (e.g. name, DOB, PAN etc.), integrated facility services, Public Financial Institution/Public Private Partnership, pure advisory service, transport of money and valuables, confidential waste, hazardous chemicals, use of drones, service rendered in remote areas.', type: 'text' },
            { key: 'hotelBvgChecklist', label: 'If service is rendered in high risk environments, background check will be done for all employees and stored locally & a BCP plan will be set up in consultation of HQ Risk team (if service is low risk answer yes & If YES for high risk, do indicate the checklist for BGV accordingly ', type: 'text' },
            { key: 'hotelOtherDetails', label: 'Other details if any:', type: 'textarea', className: 'md:col-span-2' },
          ],
        },
      ],
    },
    {
      id: 5,
      title: 'Equipment Deployment',
      description: 'Current and suggested cleaning equipment',
      hasCustomComponent: true,
      customComponentId: 'educational-equipment',
    },
    {
      id: 6,
      title: 'Manpower Deployment',
      description: 'Current and suggested manpower deployment',
      hasCustomComponent: true,
      customComponentId: 'educational-manpower',
    },
  ],
};
