import { SurveySchema } from './types';

export const siteSurveySchema: SurveySchema = {
  surveyType: 'site-survey',
  title: 'Site Survey Form',
  steps: [
    {
      id: 1,
      title: 'Site Details',
      description: 'Client and site information',
      sections: [
        {
          id: 'client-site-info',
          title: 'Client and Site Information',
          fields: [
            { key: 'clientName', label: 'Client Name', type: 'text', required: true },
            { key: 'siteName', label: 'Site Name', type: 'text', required: true },
            { key: 'surveyId', label: 'Survey ID', type: 'text' },
            { key: 'address', label: 'Address', type: 'text', required: true },
            { key: 'pincode', label: 'Pincode', type: 'text', required: true },
            { key: 'surveyDate', label: 'Survey Date', type: 'date' },
            { key: 'clientContactPersonName', label: 'Contact Person Name', type: 'text' },
            { key: 'clientContactEmail', label: 'Contact Email', type: 'email' },
            { key: 'clientContactMobile', label: 'Contact Mobile', type: 'tel' },
            {
              key: 'clientSupportNotes',
              label: 'Supporting Information',
              type: 'textarea',
              className: 'md:col-span-2',
              placeholder: 'Add any supporting information or notes',
            },
            {
              key: 'clientSupportAttachment',
              label: 'Attach Visiting Card / Supporting File',
              type: 'file',
              className: 'md:col-span-2',
            },
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Building Details',
      description: 'Building specifications',
      sections: [
        {
          id: 'plot-area',
          title: 'Plot Area',
          fields: [
            { key: 'builtUpArea', label: 'Built-up Area (sq ft)', type: 'number', placeholder: 'Enter built-up area' },
            { key: 'totalCarpetArea', label: 'Total Carpet Area (sq ft)', type: 'number', placeholder: 'Enter total carpet area' },
            { key: 'floors', label: 'Number of Floors', type: 'number', placeholder: 'Enter number of floors' },
            { key: 'workStations', label: 'Work Stations', type: 'number', placeholder: 'Enter work stations' },
          ],
        },
        {
          id: 'capacity-operations',
          title: 'Capacity & Operations',
          fields: [
            { key: 'totalEmployees', label: 'Total Employees', type: 'number', placeholder: 'Enter total employees' },
            { key: 'officeHoursFrom', label: 'Office Hours From', type: 'time' },
            { key: 'officeHoursTo', label: 'Office Hours To', type: 'time' },
            { key: 'staircases', label: 'Staircases', type: 'number', placeholder: 'Enter number of staircases' },
            { key: 'staircaseFlooring', label: 'Staircase Flooring', type: 'text', placeholder: 'Enter staircase flooring type' },
          ],
        },
        {
          id: 'common-areas',
          title: 'Common Areas',
          fields: [
            { key: 'commonArea', label: 'Common Area (sq ft)', type: 'number', placeholder: 'Enter common area' },
            { key: 'commonAreaFlooring', label: 'Common Area Flooring', type: 'text', placeholder: 'Enter flooring type' },
            { key: 'occupiedAreaFlooring', label: 'Occupied Area Flooring', type: 'text', placeholder: 'Enter flooring type' },
          ],
        },
        {
          id: 'facilities',
          title: 'Facilities',
          fields: [
            { key: 'gentToiletsCount', label: 'Gents Toilets', type: 'number', placeholder: 'Enter number of gents toilets' },
            { key: 'ladyToiletsCount', label: 'Ladies Toilets', type: 'number', placeholder: 'Enter number of ladies toilets' },
            {
              key: 'toiletries',
              label: 'Toiletries Provided',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
              ],
            },
            { key: 'basementsCount', label: 'Basements Count', type: 'number', placeholder: 'Enter number of basements' },
            { key: 'basementsUsedFor', label: 'Basements Used For', type: 'text', placeholder: 'Enter basement usage' },
            { key: 'basementsFlooring', label: 'Basements Flooring', type: 'text', placeholder: 'Enter flooring type' },
          ],
        },
        {
          id: 'parking',
          title: 'Parking',
          fields: [
            { key: 'groundLevelParking', label: 'Ground Level Parking', type: 'number', placeholder: 'Enter number of parking spaces' },
            { key: 'basementParking', label: 'Basement Parking', type: 'number', placeholder: 'Enter number of parking spaces' },
            { key: 'outsideParking', label: 'Outside Parking', type: 'number', placeholder: 'Enter number of parking spaces' },
            { key: 'visitorParking', label: 'Visitor Parking', type: 'number', placeholder: 'Enter number of parking spaces' },
          ],
        },
        {
          id: 'glass-areas',
          title: 'Glass Areas',
          fields: [
            {
              key: 'totalFacadeGlass',
              label: 'Total Façade Glass',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
              ],
            },
            {
              key: 'totalOtherGlass',
              label: 'Total Other Glass',
              type: 'select',
              options: [
                { label: 'Yes', value: 'yes' },
                { label: 'No', value: 'no' },
              ],
            },
            { key: 'electricalRoomLocation', label: 'Electrical Room Location', type: 'text', placeholder: 'Enter location' },
            {
              key: 'buildingSupportNotes',
              label: 'Supporting Information',
              type: 'textarea',
              className: 'md:col-span-2',
              placeholder: 'Add any relevant supporting information',
            },
            {
              key: 'buildingInfraAttachment',
              label: 'Attach Image of Infrastructure / Supporting File',
              type: 'file',
              className: 'md:col-span-2',
              accept: 'image/*',
            },
          ],
        },
      ],
    },
    {
      id: 3,
      title: 'Technical Details',
      description: 'Technical infrastructure',
      sections: [
        {
          id: 'electrical-power',
          title: 'Electrical Details - Power Supply',
          fields: [
            { key: 'sebLoad', label: 'SEB Sanctioned Maximum Load (HT/LT)', type: 'text' },
            { key: 'installedCapacity', label: 'Installed Capacity', type: 'text' },
            { key: 'generatorCapacity', label: 'Back-up Power - Capacity (KVA)', type: 'text' },
            { key: 'generatorBrand', label: 'Generator Brand Name', type: 'text' },
            { key: 'dgOperatingHours', label: 'Expected Average Operating Hours (DG per day)', type: 'text' },
            { key: 'dgInstallationYear', label: 'Year of DG Installation', type: 'text' },
            { key: 'fuelUsed', label: 'Fuel Used', type: 'text' },
            { key: 'fuelStorageCapacity', label: 'Capacity of Fuel Storage Tanks & Quantity', type: 'text' },
            { key: 'amfOperations', label: 'AMF Operations Available (Y/N)', type: 'text' },
            { key: 'synchronizationPanel', label: 'Synchronization Panel for Load Sharing', type: 'text' },
            { key: 'upsCapacity', label: 'Back-up UPS - Make, Quantity & Capacity', type: 'text' },
            { key: 'transformerCapacity', label: 'Transformer - Make, Quantity & Capacity', type: 'text' },
            { key: 'averageKwhCost', label: 'Average kWh Cost from Existing DG', type: 'text' },
          ],
        },
        {
          id: 'lifts-escalators',
          title: 'Lifts/Escalators',
          fields: [
            { key: 'passengerLiftsMake', label: 'Passenger Lifts - Make', type: 'text' },
            { key: 'passengerLiftsCount', label: 'Passenger Lifts - Number of Lifts', type: 'text' },
            { key: 'passengerLiftCapacityPerLift', label: 'Passenger Lifts - Capacity per Lift', type: 'text' },
            { key: 'passengerLiftWeightCapacity', label: 'Passenger Lifts - Weight Capacity', type: 'text' },
            { key: 'serviceLiftsMake', label: 'Service Lifts - Make', type: 'text' },
            { key: 'serviceLiftsCount', label: 'Service Lifts - Number of Lifts', type: 'text' },
            { key: 'serviceLiftsCapacityPerLift', label: 'Service Lifts - Capacity per Lift', type: 'text' },
            { key: 'serviceLiftsWeightCapacity', label: 'Service Lifts - Weight Capacity', type: 'text' },
          ],
        },
        {
          id: 'hvac-ac',
          title: 'HVAC - Air Conditioning System',
          fields: [
            { key: 'acType', label: 'Type of AC System (Pkg/Chiller/Split/Window)', type: 'text' },
            { key: 'acPlantCapacity', label: 'Total Plant Capacity (TR)', type: 'text' },
            { key: 'acOperatingHours', label: 'Hours of Operation for AC System', type: 'text' },
            { key: 'designTemp', label: 'Design Conditions (Temp/RH)', type: 'text' },
            { key: 'acSuppliedBy', label: 'AC Supplied By', type: 'text' },
            { key: 'acInstallationYear', label: 'Year of AC Installation', type: 'text' },
            { key: 'coolingMediaCondensers', label: 'Cooling Media of Condensers (Air/Water)', type: 'text' },
            { key: 'ahuCount', label: 'Number of AHU\'s & Capacity', type: 'text' },
            { key: 'fcuCount', label: 'Number of FCU\'s', type: 'text' },
            { key: 'condenserPumpsCapacity', label: 'Condenser Pumps (Capacity & Quantity)', type: 'text' },
            { key: 'chillerPumpsCapacity', label: 'Chiller Pumps (Capacity & Quantity)', type: 'text' },
            { key: 'coolingTowersDetails', label: 'Cooling Towers - Make, Type & Capacity', type: 'text' },
            { key: 'pipelines', label: 'Pipelines Length', type: 'text' },
          ],
        },
        {
          id: 'fire-safety',
          title: 'Fire Safety System',
          fields: [
            { key: 'sprinklerSystem', label: 'Details of Sprinkler System', type: 'text' },
            { key: 'hoseReelCount', label: 'Availability of Hose Reel Numbers on Each Floor', type: 'text' },
            { key: 'smokeDetection', label: 'Details of Smoke/Heat Detection System', type: 'text' },
            { key: 'publicAddress', label: 'Availability of Public Address System', type: 'text' },
            { key: 'pressurizedStaircases', label: 'Availability of Pressurized Staircases', type: 'text' },
            { key: 'fireSystemPumps', label: 'Details of Fire System Pumps', type: 'text' },
            { key: 'dieselPump', label: 'Diesel Pump (HP)', type: 'text' },
            { key: 'sprinklerPump', label: 'Sprinkler Pump (HP)', type: 'text' },
            { key: 'hydrantPump', label: 'Hydrant Pump (HP)', type: 'text' },
            { key: 'jockryPump', label: 'Jockey Pump (HP)', type: 'text' },
            { key: 'portableExtinguishers', label: 'Portable Extinguishers - Quantity & Make', type: 'text' },
            { key: 'fireAlarmPanel', label: 'Fire Alarm Panel Details', type: 'text' },
            { key: 'fireTankCapacity', label: 'Capacity of Tanks for Fire System', type: 'text' },
          ],
        },
        {
          id: 'building-controls',
          title: 'Building Systems & Controls',
          fields: [
            { key: 'facadeCleaningType', label: 'Façade Cleaning System (Type & Supplier)', type: 'text' },
            { key: 'buildingAccessControl', label: 'Building Access Control System (Supplier)', type: 'text' },
            { key: 'bmsMake', label: 'Building Automation System (BMS) - Make & Type', type: 'text' },
          ],
        },
        {
          id: 'water-mgmt',
          title: 'Water Availability & Management',
          fields: [
            { key: 'waterSource', label: 'Source of Water (Borewell/Corporation)', type: 'text' },
            { key: 'waterPumps', label: 'Number of Pumps with Details', type: 'text' },
            { key: 'domesticPumpDetails', label: 'Domestic Water Pump Details', type: 'text' },
            { key: 'flushingPumpDetails', label: 'Flushing Water Pump Details', type: 'text' },
            { key: 'drinkingWaterCapacity', label: 'Capacity of Domestic Water Storage Tanks', type: 'text' },
            { key: 'flushingWaterCapacity', label: 'Capacity of Flushing Water Storage Tanks', type: 'text' },
            { key: 'drinkingWaterTreated', label: 'Source of Drinking Water (Treated or Not)', type: 'text' },
          ],
        },
        {
          id: 'water-treatment',
          title: 'Water Treatment Details',
          fields: [
            { key: 'waterSoftenerCapacity', label: 'Water Softener - Make & Capacity', type: 'text' },
            { key: 'roPlantCapacity', label: 'R/O Plant - Make & Capacity', type: 'text' },
            { key: 'stpMakeType', label: 'STP - Make, Type & Capacity', type: 'text' },
          ],
        },
        {
          id: 'waste-disposal',
          title: 'Waste Disposal',
          fields: [
            { key: 'wasteType', label: 'Type of Waste', type: 'text' },
            { key: 'wasteDisposal', label: 'To be Disposed of Up To', type: 'text' },
          ],
        },
        {
          id: 'horticulture',
          title: 'Horticulture',
          fields: [
            { key: 'landscapingAreaValue', label: 'Landscaping Area', type: 'text' },
            { key: 'indoorPlantsDetails', label: 'Indoor Plants (Type & Quantity)', type: 'text' },
          ],
        },
        {
          id: 'security-system',
          title: 'Security System',
          fields: [
            { key: 'cctvCameras', label: 'CCTV (Number of Cameras)', type: 'text' },
            { key: 'mannedSecurityDesk', label: 'Manned Security Desk', type: 'text' },
            { key: 'touchDoorAlarm', label: 'Touch Door Alarm', type: 'text' },
          ],
        },
        {
          id: 'pantry-facilities',
          title: 'Pantry Facilities',
          fields: [
            { key: 'wetPantryProvided', label: 'Wet Pantry Provided (Y/N)', type: 'text' },
            { key: 'wetPantryAllowed', label: 'Wet Pantry Allowed in Space (Y/N)', type: 'text' },
            { key: 'waterSupplyLocation', label: 'Water Supply Location', type: 'text' },
            { key: 'waterDrainageLocations', label: 'Water Drainage Locations', type: 'text' },
            { key: 'cafeteriaDetails', label: 'Cafeteria Details with Occupancy & Timings', type: 'text' },
          ],
        },
        {
          id: 'remarks-comments',
          title: 'Remarks & Comments',
          fields: [
            {
              key: 'remarks',
              label: 'Remarks',
              type: 'textarea',
              className: 'md:col-span-2',
              placeholder: 'Enter any additional remarks or comments...',
            },
          ],
        },
      ],
    },
    {
      id: 4,
      title: 'Manpower Details',
      description: 'Staffing information',
      hasCustomComponent: true,
      customComponentId: 'manpower-table',
    },
  ],
};
